### ISSUE TITLE
Upgrade to support Vite 5 

### ISSUE THREAD

**Issue by metalmarker** [alexlafroscia/vite-plugin-handlebars#252]
Thank you for your awesome work on this plug-in.

After upgrading to Vite 5, the following warnings appear after startup:

`plugin 'handlebars' uses deprecated 'enforce' option. Use 'order' option instead.`
`plugin 'handlebars' uses deprecated 'transform' option. Use 'handler' option instead.`

**Comment by michaeldll** [comment]
Would appreciate this as well.

**Comment by sh-sabbir** [comment]
Just created a pr for that #253

**Comment by alexlafroscia** [comment]
This should be handled in the `2.0.0` release. Let me know if you run into any issues!
