### ISSUE TITLE
Support multiple partial directories

### ISSUE THREAD

**Issue by Bohreromir** [alexlafroscia/vite-plugin-handlebars#26]
Thanks for the Plugin,
there is one feature I'm missing. Could you add support for a list of partial directories?
Thanks

**Comment by alexlafroscia** [comment]
Yeah, that's definitely doable!

Would you imagine that you need to address the partial based on the directory it's in? Or would all of the partials end up in one top-level namespace?

I would assume the latter, but I suppose you _could_ want to do something like the former...

**Comment by Bohreromir** [comment]
All in one Namespace would be fine for me

**Comment by alexlafroscia** [comment]
Cool. Should be really easy to do then! I'll put up a PR when I have a little OSS time, and would be happy to review a PR if you want to take a crack at it instead!

**Comment by Chris2011** [comment]
Thx for the thread, I'm in the exact same situation :). Thx for the plugin btw.

**Comment by Bohreromir** [comment]
See #28

**Comment by Chris2011** [comment]
Ahh I got it a bit wrong :D. I think it is nice to have multiple partials folders, but my use case is more to have a partial folder and inside of that, are all my partials in separate folders. So I need the ability to search for partials recursively partisl/**/*

Folder structure:

```
/partials
   /header
      header.hbs
      _header.css
      metaData.json
   /footer
   ...
```

But I think I need to create another ticket for that :)

**Comment by Chris2011** [comment]
The code just goes directly into one folder and not deeper.

**Comment by alexlafroscia** [comment]
Interesting! I could see supporting sub-directories if that's useful to you (though you could also solve your use-case by configuring multiple "partials" directories, pointing directly to each sub-directory).

I'm wondering if a partial in a subdirectory should get a namespaced identifier, like `header/header` in the example @Chris2011 provided, or if it should leave the directory name out of it... I would assume, I think, that it would end up including the intermediate directory in the name of the partial when you inject it.

I wonder if Handlebars supports a `/` in a partial name...

**Comment by Chris2011** [comment]
If you could add the section to your repo "Discussions" I think it will be better there, than here to talk about it :)

**Comment by alexlafroscia** [comment]
@Chris2011 I enabled that, if you want to start a thread over there for this!

**Comment by Chris2011** [comment]
I will, that :)
