### ISSUE TITLE
Changes in linked dependencies don't cause hmr

### ISSUE THREAD

**Issue by Bohreromir** [alexlafroscia/vite-plugin-handlebars#38]
If there is a <script> or css load inside of a partial, it seems like changes in that file won't trigger a reload.

**Comment by alexlafroscia** [comment]
Hmm... That’s odd. From Vite’s perspective, the partial is _part_ of the HTML file it’s injected into, so I would expect this to work correctly.

I’ll do some investigation locally and see if I can reproduce that error; I haven’t noticed the problem myself, but I’m using Tailwind in the project I made this plugin for, so I don’t really ever edit my CSS file!

**Comment by Bohreromir** [comment]
This is what im dealing with. Changes to the scss don't trigger a reload, neither do linked scripts in the base.html when browsing to page.html.

page.html
```
{{#> base }}
    <h1> Some page content </h1>
{{/ base }}
```

base.hbs
```
[...]
<head>
     <link rel="stylesheet" href="../assets/styles/main.scss">
</head>
<body>
    {{> @partial-block }}
</body>
[...]
```

**Comment by alexlafroscia** [comment]
Can you try changing your `<link>` tag to an absolute URL rather than a relative one? Just see if that fixes things at all.

**Comment by Bohreromir** [comment]
Same behavior as before.

**Comment by alexlafroscia** [comment]
Interesting! Let's keep an eye on the Vite bug and see if that's the culprit; I don't want to shirk responsibility but it's unlikely that the issue here has something to do with this plugin since, from Vite's perspective, the resolved file with all of it's partials are just a single HTML file that it would process as usual.

**Comment by Bohreromir** [comment]
I did some test, and for me it looks like, as soon as the plugin loads hmr breaks.
This is just:
```javascript
  plugins: [
    handlebars()
  ],
```
and the default vite startertemplate:
```javascript
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="favicon.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite App</title>
  </head>
  <body>
    <div id="app"></div>
    
    <script type="module" src="/main.js"></script>
  </body>
</html>

```
vite --debug shows it recognises the changes, but doesnt know how to handle it.
![image](https://user-images.githubusercontent.com/40412303/112497322-c8905100-8d85-11eb-8612-3cbaef6352c7.png)

**Comment by alexlafroscia** [comment]
Very interesting! Thanks for investigating a bit more. My job has me pretty busy so I won't be able to look into this the next few days, during the day, at least, but I'll try to look into this more this weekend!

If you're able to post a repo somewhere with a set-up that makes it easy for me to reproduce the issue, that would go a long way toward helping me get this addressed quickly!

**Comment by Bohreromir** [comment]
Shure! https://github.com/Bohreromir/vite-hmr-bug-test
Thanks for having a look

**Comment by alexlafroscia** [comment]
Got it! Thanks!

**Comment by alexlafroscia** [comment]
Your reproduction repo was super helpful! It turns out that returning an empty array basically blocked _all_ modules from being hot-reloaded. 

I tried to write a test against this in the codebase here but there's really no way to hook in and check whether the event was emitted or not. I did try this out locally, though, and it's working now!

**Comment by alexlafroscia** [comment]
Released in `1.4.2` -- let me know if that doesn't seem to fix your issue!

**Comment by Bohreromir** [comment]
Looks good to me, thanks!

**Comment by PierreMouchan** [comment]
Hello! Seem to have the same exact bug there ;)
Here is my packages version: 
```json
    "vite-plugin-handlebars": "^1.6.0"    
    "vite": "^2.7.13"

```

**Comment by PierreMouchan** [comment]
> Hello! Seem to have the same exact bug there ;) Here is my packages version:
> 
> ```json
>     "vite-plugin-handlebars": "^1.6.0"    
>     "vite": "^2.7.13"
> ```

Problem found!
I was using type: "modules" inside my package json file
