### ISSUE TITLE
Nested Partials are Not Found

### ISSUE THREAD

**Issue by alexlafroscia** [alexlafroscia/vite-plugin-handlebars#41]
Unfortunately it doesn't work with 1.2.0 and 1.3.0. Maybe I missed smth, this is my config from the readme:

```
import { resolve } from 'path';
import handlebars from 'vite-plugin-handlebars';

export default {
  plugins: [
    handlebars({
      partialDirectory: resolve(__dirname, 'partials'),
    }),
  ],
};
```

`{{>head/head}}``this is in my startpage.html.

When I do a `yarn build` I got this error:

```
[vite:build-html] The partial head could not be found
file: C:/Projekte/Others/smth/pages/startpage/startpage.html
error during build:
Error: The partial head/head could not be found
```

_Originally posted by @Chris2011 in https://github.com/alexlafroscia/vite-plugin-handlebars/discussions/30#discussioncomment-509479_

**Comment by Chris2011** [comment]
I've added you :).

**Comment by alexlafroscia** [comment]
Thanks @Chris2011! Got it. I will hopefully find some time this weekend to dig into the issue!

**Comment by alexlafroscia** [comment]
I wasn't able to reproduce this error in the example repo, so I'm going to close this. Please re-open with a link to a minimal reproduction of the problem if anyone runs into this!

**Comment by Chris2011** [comment]
It works with 1.5.1. Thx :)

**Comment by alexlafroscia** [comment]
So glad to hear that! 🎉
